# Week 8 (Tue) - Class Activities in CS 315

You are given the file `netflix_top10_countries.tsv` in the folder data, solve the following tasks using it.

**Table of Contents**

1. [Q1: Load the file](#q1)
2. [Q2: Show number of rows](#q2)
3. [Q3: Show column names](#q3)
4. [Q4: Show number of total countries](#q4)
5. [Q5: Show number of TV series](#q5)
6. [Q6: Number of TV series in South Korea](#q6)
7. [Q7: Total weeks of Squid Games in Italy ](#q7)
8. [Q8: Time frame for a given country](#q8)
9. [Q9: Is number of weeks in ranking equal?](#q9)
10. [Q10: Country with fewest weeks](#q10)

***this is AFTER I replaced the original tsv with the most updated all-weeks-countries.tsv**

<a id="q1"></a>
### Q1: Load the file

tsv as 32 mb vs. duckdb as 7-8 mb

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('all-weeks-countries.tsv', sep='\t')
df.head()

,country_name,country_iso2,week,category,weekly_rank,show_title,season_title,cumulative_weeks_in_top_10
0,Argentina,AR,2026-10-18,Films,1,Therapy Done Right,NaN,1
1,Argentina,AR,2026-10-18,Films,2,Animals,NaN,2
2,Argentina,AR,2026-10-18,Films,3,Anyone But You,NaN,2
3,Argentina,AR,2026-10-18,Films,4,Doing Life,NaN,3
4,Argentina,AR,2026-10-18,Films,5,Ice Age: Collision Course,NaN,5

<a id="q2"></a>
### Q2: Show number of rows

In [4]:
df.shape

(515920, 8)

<a id="q3"></a>
### Q3: Show column names

In [5]:
df.columns

Index(['country_name', 'country_iso2', 'week', 'category', 'weekly_rank',
       'show_title', 'season_title', 'cumulative_weeks_in_top_10'],
      dtype='object')

<a id="q4"></a>
### Q4: Show number of total countries

In [6]:
len(df.groupby('country_name').size())

94

<a id="q5"></a>
### Q5: Show number of TV series

In [7]:
len(df.groupby('show_title').size())

12283

<a id="q6"></a>
### Q6: Number of TV series in South Korea

In [8]:
len(df[df['country_name']=='South Korea'].groupby('show_title').size())

1581

<a id="q7"></a>
### Q7: Total weeks of Squid Game in Italy

In [9]:
top_10_italy_df = df[(df['country_name'] == 'Italy') & (df['show_title'] == 'Squid Game') & (df['weekly_rank'] <= 10)]

In [10]:
top_10_italy_df.shape

(37, 8)

<a id="q8"></a>
### Q8: Time frame for a given country

Write a function that given a country name prints out the start and end date of their rankings.

Once you have created the function, call it for a few countries to test it.

In [11]:
type(df['week'])

pandas.core.series.Series

In [12]:
df['week'] = pd.to_datetime(df['week'])

In [13]:
df['week'].min

<bound method Series.min of 0        2026-10-18
1        2026-10-18
2        2026-10-18
3        2026-10-18
4        2026-10-18
            ...
515915   2021-07-04
515916   2021-07-04
515917   2021-07-04
515918   2021-07-04
515919   2021-07-04
Name: week, Length: 515920, dtype: datetime64[ns]>

This returns a whole series...

In [14]:
def show_timeframe(data, country): 
    country_df = df[df['country_name'] == country]
    start = country_df['week'].min()
    end = country_df['week'].max()
    print(f"Netflix rankings for {country} exist between {start} and {end}.")

In [15]:
show_timeframe(df,'Chile')

Netflix rankings for Chile exist between 2021-07-04 00:00:00 and 2026-10-18 00:00:00.

<a id="q9"></a>
### Q9: Is number of weeks equal for each country?

The total number of weeks in the rankings is `len(df['week'].unique())`.

The total number of countries is `len(df['country_name'].unique())`.  

For every week, each country has 20 rows.   

If they all stayed the same number of weeks, then the product of these three weeks would be the same as the total number of rows.

In [16]:
len(df['week'].unique())

277

In [17]:
len(df['country_name'].unique())

94

In [18]:
20 * len(df['country_name'].unique()) == len(df['week'].unique())

False

We should have expected this to be `False` since we saw in Q8 that Russia stopped being in the rankings after it attacked Ukraine in February 2022.

<a id="q10"></a>
### Q10: Country with fewest weeks

Write a one-liner that will show the country with the fewest weeks in the Netflix rankings

In [19]:
df.groupby('country_name')['week'].nunique().sort_values()

country_name
Russia          35
Portugal       277
Poland         277
Philippines    277
Peru           277
              ...
Guadeloupe     277
Greece         277
Germany        277
Indonesia      277
Vietnam        277
Name: week, Length: 94, dtype: int64

We can see that Russia is less represented in this dataset.

# TASK 2

***New function: rank2score***

In [20]:
def rank2score(rank):
    if rank == 1:
        score = 25
    elif rank == 2:
        score = 18
    elif rank == 3: 
        score = 15
    elif rank == 4:
        score = 12
    elif rank == 5: 
        score = 10
    elif rank == 6:
        score = 8 
    elif rank == 7: 
        score = 6
    elif rank == 8:
        score = 4
    elif rank == 9:
        score = 2
    elif rank == 10:
        score = 1
    return score

In [21]:
df.head()

,country_name,country_iso2,week,category,weekly_rank,show_title,season_title,cumulative_weeks_in_top_10
0,Argentina,AR,2026-10-18,Films,1,Therapy Done Right,NaN,1
1,Argentina,AR,2026-10-18,Films,2,Animals,NaN,2
2,Argentina,AR,2026-10-18,Films,3,Anyone But You,NaN,2
3,Argentina,AR,2026-10-18,Films,4,Doing Life,NaN,3
4,Argentina,AR,2026-10-18,Films,5,Ice Age: Collision Course,NaN,5

In [23]:
df['score'] = df['weekly_rank'].apply(rank2score)
df.head()

,country_name,country_iso2,week,category,weekly_rank,show_title,season_title,cumulative_weeks_in_top_10,score
0,Argentina,AR,2026-10-18,Films,1,Therapy Done Right,NaN,1,25
1,Argentina,AR,2026-10-18,Films,2,Animals,NaN,2,18
2,Argentina,AR,2026-10-18,Films,3,Anyone But You,NaN,2,15
3,Argentina,AR,2026-10-18,Films,4,Doing Life,NaN,3,12
4,Argentina,AR,2026-10-18,Films,5,Ice Age: Collision Course,NaN,5,10

Removing the useless columns:

In [24]:
df = df.drop(columns=['country_iso2', 'category', 'season_title'])

In [25]:
df.head()

,country_name,week,weekly_rank,show_title,cumulative_weeks_in_top_10,score
0,Argentina,2026-10-18,1,Therapy Done Right,1,25
1,Argentina,2026-10-18,2,Animals,2,18
2,Argentina,2026-10-18,3,Anyone But You,2,15
3,Argentina,2026-10-18,4,Doing Life,3,12
4,Argentina,2026-10-18,5,Ice Age: Collision Course,5,10

In [41]:
lr_df = df[df['show_title']== 'Lovely Runner']
lr_df.shape

(51, 6)

In [42]:
lr_df.head()

,country_name,week,weekly_rank,show_title,cumulative_weeks_in_top_10,score
29974,Bangladesh,2024-08-18,5,Lovely Runner,3,10
29993,Bangladesh,2024-08-11,4,Lovely Runner,2,12
30015,Bangladesh,2024-08-04,6,Lovely Runner,1,8
185097,India,2024-08-18,8,Lovely Runner,3,4
185113,India,2024-08-11,4,Lovely Runner,2,12

There are 51 rows with Lovely Runner.

Total score:

In [54]:
lr_df_stats = lr_df.groupby('country_name')['score'].sum().rename('total_score').reset_index()
lr_df_stats

   country_name  total_score
0    Bangladesh           30
1         India           26
2     Indonesia           69
3      Malaysia           62
4      Maldives           32
5      Pakistan            6
6   Philippines           41
7     Singapore           20
8   South Korea           18
9     Sri Lanka           32
10       Taiwan           10
11     Thailand           20
12      Vietnam           75

Total weeks:

In [55]:
lr_df_stats['total_weeks']= lr_df.groupby('country_name')['week'].count().rename('total_weeks').reset_index()['total_weeks']
lr_df_stats

   country_name  total_score  total_weeks
0    Bangladesh           30            3
1         India           26            3
2     Indonesia           69            7
3      Malaysia           62            6
4      Maldives           32            4
5      Pakistan            6            1
6   Philippines           41            4
7     Singapore           20            4
8   South Korea           18            3
9     Sri Lanka           32            4
10       Taiwan           10            2
11     Thailand           20            3
12      Vietnam           75            7

Rankings_list

In [57]:
lr_df_stats['rankings_list'] = lr_df.groupby('country_name')['weekly_rank'].agg(list).rename('rankings_list').reset_index()['rankings_list']
lr_df_stats

   country_name  total_score  total_weeks          rankings_list
0    Bangladesh           30            3              [5, 4, 6]
1         India           26            3              [8, 4, 5]
2     Indonesia           69            7  [9, 7, 6, 7, 4, 1, 5]
3      Malaysia           62            6     [9, 9, 7, 3, 1, 4]
4      Maldives           32            4          [10, 6, 3, 6]
5      Pakistan            6            1                    [7]
6   Philippines           41            4           [7, 5, 3, 5]
7     Singapore           20            4           [9, 7, 5, 9]
8   South Korea           18            3              [9, 7, 5]
9     Sri Lanka           32            4          [10, 7, 3, 5]
10       Taiwan           10            2                 [7, 8]
11     Thailand           20            3              [7, 8, 5]
12      Vietnam           75            7  [8, 7, 6, 5, 4, 1, 5]

In [62]:
lr_df_stats.sort_values(by='total_score', ascending=False)

   country_name  total_score  total_weeks          rankings_list
12      Vietnam           75            7  [8, 7, 6, 5, 4, 1, 5]
2     Indonesia           69            7  [9, 7, 6, 7, 4, 1, 5]
3      Malaysia           62            6     [9, 9, 7, 3, 1, 4]
6   Philippines           41            4           [7, 5, 3, 5]
4      Maldives           32            4          [10, 6, 3, 6]
9     Sri Lanka           32            4          [10, 7, 3, 5]
0    Bangladesh           30            3              [5, 4, 6]
1         India           26            3              [8, 4, 5]
7     Singapore           20            4           [9, 7, 5, 9]
11     Thailand           20            3              [7, 8, 5]
8   South Korea           18            3              [9, 7, 5]
10       Taiwan           10            2                 [7, 8]
5      Pakistan            6            1                    [7]

I had to look up how to use agg(list).

### Running on dramas I'm interested in

In [59]:
df['week'].describe()

count                           515920
mean     2024-02-23 20:25:08.326872576
min                2021-07-04 00:00:00
25%                2022-10-23 00:00:00
50%                2024-02-25 00:00:00
75%                2025-06-22 00:00:00
max                2026-10-18 00:00:00
Name: week, dtype: object

***True Beauty***

I personally liked this a lot and it's based on a webtoon and the whole focus point is the main selling point of Korean culture (rich pretty boy, plastic surgery/makeup, idol trainee...)

In [60]:
tb_df = df[df['show_title']== 'True Beauty']
tb_df.shape

(489, 6)

In [64]:
tb_df_stats = tb_df.groupby('country_name')['score'].sum().rename('total_score').reset_index()
tb_df_stats['total_weeks']= tb_df.groupby('country_name')['week'].count().rename('total_weeks').reset_index()['total_weeks']
tb_df_stats['rankings_list'] = tb_df.groupby('country_name')['weekly_rank'].agg(list).rename('rankings_list').reset_index()['rankings_list']
tb_df_stats.sort_values(by='total_score', ascending=False)

,country_name,total_score,total_weeks,rankings_list
3,Bangladesh,215,18,"[9, 8, 6, 6, 5, 5, 5, 6, 5, 4, 4, 5, 5, 6, 1, ..."
4,Bolivia,191,25,"[10, 10, 8, 9, 10, 6, 8, 10, 10, 8, 9, 7, 8, 5..."
38,Philippines,180,14,"[10, 9, 6, 5, 7, 3, 4, 5, 3, 3, 2, 2, 1, 1]"
41,Saudi Arabia,178,17,"[10, 8, 9, 9, 10, 8, 8, 4, 4, 5, 5, 4, 2, 1, 1..."
33,Oman,178,18,"[10, 10, 8, 9, 8, 9, 10, 8, 4, 5, 6, 7, 6, 3, ..."
37,Peru,163,18,"[8, 9, 10, 10, 9, 10, 5, 7, 6, 7, 4, 5, 6, 3, ..."
24,Maldives,153,15,"[10, 9, 9, 7, 8, 6, 3, 6, 6, 6, 6, 3, 2, 1, 1]"
23,Malaysia,142,14,"[10, 8, 7, 9, 8, 6, 6, 5, 6, 6, 3, 2, 1, 1]"
10,Ecuador,138,17,"[10, 10, 9, 9, 10, 6, 7, 6, 8, 5, 6, 8, 6, 5, ..."
39,Qatar,137,12,"[10, 8, 7, 5, 6, 6, 7, 6, 2, 2, 1, 1]"
21,Kuwait,127,14,"[10, 10, 7, 8, 5, 5, 7, 6, 8, 6, 3, 2, 2, 2]"
45,Sri Lanka,125,11,"[7, 4, 5, 6, 7, 8, 9, 4, 3, 1, 1]"
31,Nicaragua,124,20,"[8, 10, 10, 9, 9, 10, 8, 9, 7, 9, 8, 9, 8, 8, ..."
49,United Arab Emirates,123,10,"[8, 5, 7, 7, 8, 7, 4, 1, 1, 1]"
27,Mexico,121,18,"[9, 8, 10, 8, 9, 10, 10, 9, 8, 9, 7, 10, 8, 5,..."
14,Guatemala,112,13,"[10, 10, 8, 8, 7, 7, 10, 8, 5, 5, 3, 1, 1]"
6,Chile,111,9,"[9, 6, 7, 6, 5, 4, 3, 1, 1]"
2,Bahrain,110,10,"[7, 5, 6, 7, 7, 6, 4, 2, 2, 2]"
32,Nigeria,109,11,"[10, 6, 9, 8, 10, 9, 6, 3, 2, 1, 1]"
47,Thailand,109,12,"[8, 10, 8, 6, 7, 7, 7, 7, 5, 3, 2, 1]"
12,El Salvador,102,14,"[10, 10, 10, 9, 9, 9, 8, 9, 8, 6, 5, 3, 1, 1]"
15,Honduras,101,12,"[8, 10, 8, 10, 8, 9, 9, 6, 5, 3, 1, 1]"
7,Colombia,100,10,"[8, 10, 9, 7, 8, 6, 5, 3, 1, 1]"
17,India,99,18,"[10, 9, 8, 8, 10, 10, 8, 10, 9, 6, 6, 8, 10, 1..."
18,Indonesia,94,12,"[10, 10, 6, 10, 9, 10, 8, 9, 4, 4, 1, 1]"
19,Jordan,82,6,"[9, 8, 3, 2, 1, 2]"
28,Morocco,79,8,"[10, 10, 6, 7, 4, 2, 2, 3]"
42,Singapore,76,8,"[10, 8, 8, 8, 3, 4, 2, 2]"
36,Paraguay,76,7,"[10, 9, 6, 5, 4, 1, 2]"
51,Venezuela,70,5,"[8, 6, 3, 1, 2]"
8,Costa Rica,70,6,"[10, 5, 6, 3, 2, 2]"
35,Panama,66,6,"[10, 7, 6, 3, 2, 2]"
34,Pakistan,64,11,"[10, 10, 8, 10, 9, 10, 8, 6, 4, 3, 3]"
9,Dominican Republic,62,6,"[8, 7, 5, 4, 3, 3]"
11,Egypt,60,6,"[10, 9, 7, 2, 2, 3]"
52,Vietnam,58,6,"[8, 9, 4, 5, 3, 3]"
5,Brazil,57,5,"[7, 4, 3, 4, 4]"
16,Hong Kong,54,5,"[9, 5, 4, 3, 3]"
0,Argentina,49,5,"[9, 5, 5, 4, 3]"
20,Kenya,47,4,"[10, 5, 2, 2]"
26,Mauritius,43,4,"[10, 7, 2, 2]"
46,Taiwan,42,4,"[6, 5, 4, 4]"
43,South Africa,34,3,"[8, 3, 3]"
30,New Zealand,30,2,"[3, 3]"
22,Lebanon,29,3,"[7, 3, 6]"
40,Réunion,26,3,"[8, 5, 4]"
1,Australia,25,2,"[3, 5]"
29,New Caledonia,24,3,"[7, 6, 5]"
44,South Korea,22,3,"[8, 6, 5]"
50,Uruguay,8,2,"[9, 7]"
48,Turkey,6,2,"[9, 8]"
25,Martinique,2,1,[9]
13,France,1,1,[10]

***The Glory***

A huge hit everywhere based on real-life events and Korean bullying (quite infamous).

In [65]:
tg_df = df[df['show_title']== 'The Glory']
tg_df.shape

(601, 6)

In [66]:
tg_df_stats = tg_df.groupby('country_name')['score'].sum().rename('total_score').reset_index()
tg_df_stats['total_weeks']= tg_df.groupby('country_name')['week'].count().rename('total_weeks').reset_index()['total_weeks']
tg_df_stats['rankings_list'] = tg_df.groupby('country_name')['weekly_rank'].agg(list).rename('rankings_list').reset_index()['rankings_list']
tg_df_stats.sort_values(by='total_score', ascending=False)

,country_name,total_score,total_weeks,rankings_list
81,Taiwan,352,23,"[10, 4, 3, 2, 5, 10, 6, 4, 2, 2, 1, 1, 1, 5, 7..."
29,Hong Kong,345,25,"[7, 6, 8, 9, 7, 9, 4, 4, 3, 2, 2, 1, 1, 1, 1, ..."
90,Vietnam,312,21,"[10, 9, 6, 4, 4, 4, 2, 1, 1, 1, 1, 9, 8, 7, 6,..."
76,South Korea,298,20,"[8, 10, 8, 6, 3, 2, 1, 1, 1, 1, 5, 6, 8, 6, 5,..."
33,Indonesia,294,20,"[8, 6, 5, 6, 4, 2, 2, 1, 1, 1, 8, 9, 8, 6, 3, ..."
...,...,...,...,...
34,Ireland,10,1,[5]
31,Iceland,8,1,[6]
42,Latvia,8,1,[6]
77,Spain,4,1,[8]
74,Slovenia,2,1,[9]

So interesting.... top-viewing countries are East Asian countries that are super high-pressure environments.

***Squid Game***

This is probably the culmination of both squid game 1 and 2.

In [83]:
sg_df = df[df['show_title'] == 'Squid Game']
sg_df.shape

(3247, 6)

In [81]:
sg_df_stats = sg_df.groupby('country_name')['score'].sum().rename('total_score').reset_index()
sg_df_stats['total_weeks']= sg_df.groupby('country_name')['week'].count().rename('total_weeks').reset_index()['total_weeks']
sg_df_stats['rankings_list'] = sg_df.groupby('country_name')['weekly_rank'].agg(list).rename('rankings_list').reset_index()['rankings_list']
sg_df_stats.sort_values(by='total_score', ascending=False)

,country_name,total_score,total_weeks,rankings_list
33,India,816,69,"[9, 9, 4, 4, 10, 3, 7, 9, 2, 5, 6, 1, 4, 5, 1,..."
61,Pakistan,808,66,"[10, 9, 6, 9, 3, 6, 7, 2, 5, 7, 1, 4, 5, 1, 3,..."
5,Bangladesh,807,66,"[9, 8, 8, 5, 4, 7, 1, 5, 9, 1, 4, 6, 1, 3, 4, ..."
40,Jordan,772,50,"[9, 8, 4, 6, 4, 3, 7, 1, 6, 7, 1, 2, 3, 1, 2, ..."
7,Bolivia,760,52,"[10, 7, 6, 2, 8, 2, 6, 9, 1, 4, 5, 1, 2, 3, 1,..."
...,...,...,...,...
27,Guadeloupe,307,21,"[10, 5, 1, 1, 8, 1, 9, 3, 1, 6, 1, 5, 10, 7, 6..."
35,Ireland,302,20,"[9, 5, 2, 1, 1, 5, 6, 3, 10, 2, 6, 1, 10, 5, 3..."
50,Martinique,298,20,"[5, 1, 1, 8, 1, 9, 3, 1, 6, 1, 5, 10, 9, 7, 5,..."
3,Bahamas,285,18,"[2, 1, 1, 5, 3, 1, 5, 1, 7, 10, 5, 4, 4, 3, 2,..."
70,Russia,274,19,"[9, 10, 7, 5, 5, 4, 5, 4, 4, 7, 5, 3, 1, 1, 1,..."

***weak hero class 1***

Action, also based on bullying but shows more of the resistance; also based on webtoon. Very masculine.

In [68]:
wh_df = df[df['show_title'] == 'Weak Hero']
wh_df.shape

(393, 6)

In [69]:
wh_df_stats = wh_df.groupby('country_name')['score'].sum().rename('total_score').reset_index()
wh_df_stats['total_weeks']= wh_df.groupby('country_name')['week'].count().rename('total_weeks').reset_index()['total_weeks']
wh_df_stats['rankings_list'] = wh_df.groupby('country_name')['weekly_rank'].agg(list).rename('rankings_list').reset_index()['rankings_list']
wh_df_stats.sort_values(by='total_score', ascending=False)

,country_name,total_score,total_weeks,rankings_list
26,Indonesia,175,12,"[8, 6, 3, 7, 1, 4, 1, 4, 5, 3, 2, 1]"
36,Malaysia,174,11,"[9, 3, 6, 1, 4, 1, 4, 5, 3, 1, 1]"
51,Philippines,167,11,"[7, 1, 6, 1, 2, 1, 4, 7, 7, 2, 2]"
61,South Korea,155,17,"[8, 10, 6, 7, 8, 8, 10, 4, 7, 1, 5, 1, 8, 8, 6..."
47,Pakistan,148,17,"[9, 10, 5, 8, 9, 6, 10, 4, 5, 2, 4, 2, 6, 5, 9..."
...,...,...,...,...
60,South Africa,7,3,"[9, 10, 8]"
58,Serbia,5,2,"[10, 8]"
66,Trinidad and Tobago,4,1,[8]
17,Estonia,2,1,[9]
12,Czech Republic,1,1,[10]

**When Life Gives You Tangerines**

In [70]:
wl_df = df[df['show_title'] == 'When Life Gives You Tangerines']
wl_df.shape

(344, 6)

In [71]:
wl_df_stats = wl_df.groupby('country_name')['score'].sum().rename('total_score').reset_index()
wl_df_stats['total_weeks']= wl_df.groupby('country_name')['week'].count().rename('total_weeks').reset_index()['total_weeks']
wl_df_stats['rankings_list'] = wl_df.groupby('country_name')['weekly_rank'].agg(list).rename('rankings_list').reset_index()['rankings_list']
wl_df_stats.sort_values(by='total_score', ascending=False)

,country_name,total_score,total_weeks,rankings_list
2,Bangladesh,219,21,"[10, 10, 10, 10, 9, 7, 5, 3, 4, 6, 4, 4, 3, 3,..."
37,Taiwan,192,11,"[10, 7, 4, 4, 2, 1, 1, 1, 1, 1, 2]"
35,South Korea,185,14,"[8, 10, 9, 9, 6, 6, 6, 4, 3, 1, 1, 1, 1, 1]"
42,Vietnam,170,10,"[8, 6, 5, 3, 2, 1, 1, 1, 1, 3]"
16,Indonesia,166,9,"[8, 6, 2, 2, 1, 2, 1, 1, 1]"
31,Philippines,161,9,"[10, 7, 2, 2, 1, 1, 1, 1, 2]"
30,Peru,158,12,"[10, 7, 5, 5, 5, 3, 1, 2, 3, 2, 2, 4]"
15,India,156,14,"[8, 5, 7, 4, 3, 4, 5, 3, 3, 3, 4, 5, 2, 9]"
14,Hong Kong,147,10,"[9, 7, 6, 4, 3, 2, 2, 2, 1, 1]"
20,Malaysia,140,10,"[8, 9, 5, 3, 2, 2, 3, 2, 1, 3]"
38,Thailand,132,9,"[10, 8, 6, 2, 2, 2, 1, 1, 3]"
3,Bolivia,124,10,"[7, 7, 6, 6, 2, 2, 2, 2, 2, 7]"
34,Singapore,107,10,"[10, 10, 9, 5, 4, 3, 3, 3, 2, 2]"
11,El Salvador,104,10,"[10, 8, 7, 4, 4, 2, 3, 2, 4, 7]"
32,Qatar,101,8,"[9, 5, 5, 2, 3, 2, 2, 5]"
27,Pakistan,100,12,"[9, 10, 9, 7, 6, 4, 4, 4, 5, 6, 4, 3]"
9,Ecuador,97,8,"[6, 7, 6, 3, 2, 3, 3, 4]"
13,Honduras,92,9,"[9, 8, 4, 5, 2, 3, 3, 4, 8]"
24,Nicaragua,88,9,"[8, 8, 6, 5, 3, 3, 2, 4, 9]"
36,Sri Lanka,81,9,"[8, 6, 7, 7, 6, 4, 3, 4, 5]"
12,Guatemala,81,9,"[8, 7, 7, 4, 2, 4, 4, 5, 10]"
22,Mexico,74,9,"[10, 8, 8, 8, 3, 2, 5, 4, 7]"
5,Chile,73,9,"[10, 7, 10, 9, 4, 2, 4, 3, 7]"
26,Oman,72,9,"[10, 8, 5, 7, 4, 6, 4, 3, 8]"
40,United Arab Emirates,72,8,"[10, 8, 7, 3, 5, 3, 3, 7]"
21,Maldives,69,7,"[8, 7, 5, 4, 4, 5, 3]"
33,Saudi Arabia,64,7,"[8, 6, 5, 6, 3, 2, 10]"
19,Kuwait,63,7,"[10, 10, 6, 5, 3, 2, 5]"
29,Paraguay,58,6,"[8, 4, 4, 4, 4, 7]"
1,Bahrain,43,6,"[9, 6, 6, 6, 3, 9]"
41,Venezuela,40,6,"[8, 5, 5, 5, 8, 9]"
6,Colombia,40,5,"[7, 6, 7, 5, 5]"
7,Costa Rica,38,5,"[5, 7, 4, 6, 9]"
17,Japan,31,6,"[10, 5, 6, 9, 7, 8]"
28,Panama,25,5,"[5, 7, 7, 9, 10]"
18,Jordan,25,5,"[10, 8, 8, 8, 4]"
23,Morocco,25,4,"[10, 7, 6, 5]"
4,Brazil,24,4,"[7, 7, 7, 7]"
8,Dominican Republic,11,4,"[8, 9, 10, 8]"
0,Argentina,10,2,"[8, 7]"
39,Turkey,10,3,"[8, 9, 8]"
10,Egypt,7,2,"[10, 7]"
25,Nigeria,7,2,"[10, 7]"

***Twenty Five Twenty One***

In [73]:
tf_df = df[df['show_title'] == 'Twenty Five Twenty One']
tf_df.shape

(245, 6)

In [76]:
tf_df.head()

,country_name,week,weekly_rank,show_title,cumulative_weeks_in_top_10,score
26877,Bahrain,2022-04-17,8,Twenty Five Twenty One,5,4
26893,Bahrain,2022-04-10,4,Twenty Five Twenty One,4,12
26913,Bahrain,2022-04-03,4,Twenty Five Twenty One,3,12
26934,Bahrain,2022-03-27,5,Twenty Five Twenty One,2,10
26955,Bahrain,2022-03-20,6,Twenty Five Twenty One,1,8

In [75]:
tf_df_stats = tf_df.groupby('country_name')['score'].sum().rename('total_score').reset_index()
tf_df_stats['total_weeks']= tf_df.groupby('country_name')['week'].count().rename('total_weeks').reset_index()['total_weeks']
tf_df_stats['rankings_list'] = tf_df.groupby('country_name')['weekly_rank'].agg(list).rename('rankings_list').reset_index()['rankings_list']
tf_df_stats.sort_values(by='total_score', ascending=False)

,country_name,total_score,total_weeks,rankings_list
27,South Korea,224,15,"[10, 10, 8, 6, 6, 4, 2, 1, 1, 1, 1, 2, 2, 2, 2]"
9,Indonesia,202,15,"[9, 7, 6, 7, 6, 3, 3, 2, 2, 2, 2, 2, 1, 3, 4]"
23,Philippines,181,13,"[7, 5, 4, 3, 3, 2, 2, 2, 2, 3, 2, 4, 7]"
32,Vietnam,176,14,"[10, 8, 6, 7, 4, 3, 2, 2, 2, 2, 3, 3, 2, 5]"
29,Taiwan,170,17,"[10, 10, 9, 8, 5, 5, 4, 2, 2, 2, 2, 3, 4, 4, 5..."
13,Malaysia,163,12,"[10, 6, 4, 3, 2, 2, 2, 2, 2, 2, 3, 8]"
30,Thailand,152,14,"[9, 7, 10, 8, 4, 3, 2, 2, 2, 3, 5, 5, 3, 6]"
7,Hong Kong,140,12,"[10, 7, 5, 2, 2, 2, 2, 3, 4, 4, 6, 8]"
1,Bangladesh,132,13,"[8, 8, 7, 6, 5, 5, 3, 3, 3, 3, 5, 5, 5]"
25,Saudi Arabia,113,11,"[7, 6, 5, 3, 3, 3, 2, 7, 5, 6, 9]"
26,Singapore,107,10,"[10, 7, 4, 2, 3, 3, 2, 4, 8, 7]"
10,Japan,88,11,"[10, 8, 5, 4, 3, 4, 5, 6, 6, 7, 9]"
24,Qatar,82,10,"[9, 7, 7, 3, 3, 4, 3, 6, 9, 10]"
14,Maldives,73,9,"[10, 8, 7, 3, 3, 3, 4, 8, 10]"
28,Sri Lanka,68,8,"[9, 7, 4, 3, 3, 5, 9, 7]"
8,India,65,7,"[7, 4, 3, 5, 5, 9, 5]"
20,Oman,62,5,"[3, 3, 3, 3, 9]"
31,United Arab Emirates,59,8,"[8, 4, 4, 4, 5, 9, 10, 7]"
12,Kuwait,53,6,"[8, 3, 4, 4, 6, 9]"
0,Bahrain,46,5,"[8, 4, 4, 5, 6]"
22,Peru,37,8,"[9, 6, 5, 5, 9, 9, 9, 10]"
11,Jordan,23,3,"[10, 4, 5]"
4,Egypt,22,3,"[7, 4, 8]"
21,Pakistan,20,4,"[8, 5, 8, 9]"
2,Bolivia,17,4,"[8, 7, 7, 10]"
15,Mexico,4,1,[8]
19,Nigeria,1,1,[10]
18,Nicaragua,1,1,[10]
17,New Caledonia,1,1,[10]
6,Guatemala,1,1,[10]
5,El Salvador,1,1,[10]
3,Ecuador,1,1,[10]
16,Morocco,1,1,[10]

***The Good Bad Mother***

In [77]:
mother_df = df[df['show_title'] == 'The Good Bad Mother']
mother_df.shape

(191, 6)

In [78]:
mother_df_stats = mother_df.groupby('country_name')['score'].sum().rename('total_score').reset_index()
mother_df_stats['total_weeks']= mother_df.groupby('country_name')['week'].count().rename('total_weeks').reset_index()['total_weeks']
mother_df_stats['rankings_list'] = mother_df.groupby('country_name')['weekly_rank'].agg(list).rename('rankings_list').reset_index()['rankings_list']
mother_df_stats.sort_values(by='total_score', ascending=False)

,country_name,total_score,total_weeks,rankings_list
11,Indonesia,162,11,"[8, 7, 5, 3, 1, 2, 2, 2, 2, 2, 4]"
33,Vietnam,137,10,"[10, 7, 4, 1, 2, 2, 2, 2, 3, 7]"
15,Malaysia,134,10,"[9, 6, 4, 2, 2, 2, 2, 2, 2, 8]"
28,South Korea,123,9,"[8, 5, 2, 2, 2, 3, 3, 3, 5]"
24,Philippines,115,8,"[6, 3, 1, 2, 3, 4, 4, 5]"
9,Hong Kong,99,8,"[9, 8, 2, 2, 2, 2, 3, 7]"
27,Singapore,93,8,"[9, 6, 2, 3, 3, 3, 4, 6]"
31,Thailand,85,8,"[10, 7, 2, 3, 3, 4, 5, 6]"
30,Taiwan,83,8,"[7, 4, 2, 3, 3, 6, 6, 10]"
2,Bolivia,69,7,"[6, 3, 5, 5, 4, 6, 7]"
26,Saudi Arabia,64,6,"[8, 2, 4, 5, 5, 5]"
1,Bangladesh,54,5,"[4, 6, 4, 5, 4]"
23,Peru,53,7,"[7, 3, 6, 7, 5, 8, 8]"
25,Qatar,49,6,"[4, 6, 4, 5, 7, 10]"
16,Maldives,46,5,"[4, 6, 6, 5, 6]"
21,Oman,45,6,"[10, 4, 6, 5, 6, 7]"
0,Bahrain,38,5,"[4, 6, 6, 6, 9]"
14,Kuwait,38,5,"[4, 6, 6, 6, 9]"
12,Japan,34,5,"[5, 5, 7, 7, 9]"
32,United Arab Emirates,31,5,"[5, 7, 7, 6, 10]"
29,Sri Lanka,29,5,"[5, 7, 7, 7, 10]"
10,India,23,4,"[7, 6, 6, 10]"
6,El Salvador,19,5,"[6, 9, 7, 9, 10]"
8,Honduras,18,4,"[6, 9, 7, 9]"
17,Mexico,18,6,"[10, 9, 10, 6, 8, 9]"
7,Guatemala,14,5,"[6, 9, 9, 10, 10]"
20,Nigeria,14,3,"[6, 8, 9]"
18,Morocco,12,3,"[7, 8, 9]"
13,Jordan,11,3,"[8, 7, 10]"
19,Nicaragua,10,5,"[8, 9, 9, 10, 10]"
4,Ecuador,5,3,"[9, 9, 10]"
5,Egypt,4,1,[8]
22,Pakistan,1,1,[10]
3,Chile,1,1,[10]