# SQL vs. pandas Mini-tutorial

This tutorial is based on this YouTube Video: [SQL for Beginners in 15 minutes](https://www.youtube.com/watch?v=_vxobA36UN4).  
Please speed watch the video first, to get an overall sense of its content, then as you do the examples below, rewatch the specific portions, since you are replicating the examples in Python.

I have created the DB file, named "school_database.db", containing the two tables of the video. We also have access to the two tables as CSV files. Below we will show how to operate with data both in pandas and SQL.

**NOTE:** Throughout the tutorials there are **tasks** for you to complete, typically labeled as **Task for you**.

**Table of Content**

1. [Loading the data](#sec1)
2. [The `SELECT * FROM` command](#sec2)
3. [The `SELECT ... FROM` command](#sec3)
4. [The `SELECT ... FROM ... WHERE` command](#sec4)
5. [Sorting with `ORDER BY`](#sec5)
6. [Exercise: Combine all commands](#sec6)
7. [The GROUP BY command](#sec7)
8. [Filtering aggregated data with `HAVING`](#sec8)
9. [Utility keywords](#sec9)
10. [Combining Tables]()

<a id="sec1"></a>
## 1. Loading the data

Load the two CSV tables that we will use with `pandas`

In [1]:
import pandas as pd
import numpy as np

### Load the table `students`

In [12]:
students_df = pd.read_csv('students.csv', 
                          index_col='id')
students_df.head()

,student_name,grade_level,gpa,school_lunch,birthday,email
id,,,,,,
1,Abby Johnson,10,3.1,Yes,5/14/08,abby.johnson@mavenhighschool.com
2,Bob Smith,11,3.1,No,9/30/07,bob.smith@mavenhighschool.com
3,Catherine Davis,12,3.6,Yes,11/21/06,catherine.davis@mavenhighschool.com
4,Daniel Brown,9,3.5,Yes,3/10/09,daniel.brown@mavenhighschool.com
5,Eva Martinez,10,2.7,No,2/5/08,eva.martinez@mavenhighschool.com

**Task for you:** Load the data without `index_col` parameter, what do you notice?

In [5]:
test_df = pd.read_csv('students.csv')
test_df.head()

,id,student_name,grade_level,gpa,school_lunch,birthday,email
0,1,Abby Johnson,10,3.1,Yes,5/14/08,abby.johnson@mavenhighschool.com
1,2,Bob Smith,11,3.1,No,9/30/07,bob.smith@mavenhighschool.com
2,3,Catherine Davis,12,3.6,Yes,11/21/06,catherine.davis@mavenhighschool.com
3,4,Daniel Brown,9,3.5,Yes,3/10/09,daniel.brown@mavenhighschool.com
4,5,Eva Martinez,10,2.7,No,2/5/08,eva.martinez@mavenhighschool.com

This creates a new column of id and the index now starts from 0 instead of 1.

### Load the table `student_grades`

In [7]:
student_grades_df = pd.read_csv("student_grades.csv")
student_grades_df.head()

  semester_id  class_id department class_name  student_id  final_grade
0    SPR_2024       101       Math    Algebra           4         85.0
1    SPR_2024       101       Math    Algebra           8         76.0
2    SPR_2024       101       Math    Algebra          11         90.0
3    SPR_2024       101       Math    Algebra          15         97.0
4    SPR_2024       102       Math   Geometry           1         93.0

### Connect to the database

Python has its own built-in library that manages SQLite databases (one of the light-weight RDBMSs). This library is `sqlite3` and will execute the SQL queries for us.

In [8]:
import sqlite3

db_file = "school_database.db"

conn = sqlite3.connect(db_file) # you are connected to the database
cursor = conn.cursor() # you have appointed a "helper" that will perform SQL commands for you
cursor

<a id="sec2"></a>
## 2. The `SELECT * FROM` command

The command `SELECT * from students` gives us the whole table.

In [13]:
query = "SELECT * from students"
cursor.execute(query) # the cursor goes to the location in the database where the data is
cursor.fetchall() # we have to explicetely ask for the data to be feteched

[(1,
  'Abby Johnson',
  10,
  3.1,
  'Yes',
  '2008-05-14',
  'abby.johnson@mavenhighschool.com'),
 (2,
  'Bob Smith',
  11,
  3.1,
  'No',
  '2007-09-30',
  'bob.smith@mavenhighschool.com'),
 (3,
  'Catherine Davis',
  12,
  3.6,
  'Yes',
  '2006-11-21',
  'catherine.davis@mavenhighschool.com'),
 (4,
  'Daniel Brown',
  9,
  3.5,
  'Yes',
  '2009-03-10',
  'daniel.brown@mavenhighschool.com'),
 (5,
  'Eva Martinez',
  10,
  2.7,
  'No',
  '2008-02-05',
  'eva.martinez@mavenhighschool.com'),
 (6,
  'Frank Wilson',
  11,
  3.2,
  'No',
  '2007-07-17',
  'frank.wilson@mavenhighschool.com'),
 (7,
  'Grace Lee',
  12,
  3.0,
  'Yes',
  '2006-12-02',
  'grace.lee@mavenhighschool.com'),
 (8,
  'Henry Taylor',
  9,
  3.0,
  'Yes',
  '2009-06-08',
  'henry.taylor@mavenhighschool.com'),
 (9,
  'Isabella Moore',
  10,
  2.8,
  'Yes',
  '2008-01-19',
  'isabella.moore@mavenhighschool.com'),
 (10,
  'Jack Thompson',
  11,
  2.9,
  'Yes',
  '2007-04-25',
  'jack.thompson@mavenhighschool.com'),
 (11,
  'Karen White',
  9,
  3.4,
  'No',
  '2009-09-10',
  'karen.white@mavenhighschool.com'),
 (12,
  'Liam Green',
  10,
  4.0,
  'Yes',
  '2008-08-03',
  'liam.green@mavenhighschool.com'),
 (13,
  'Mia Harris',
  11,
  3.0,
  'No',
  '2007-02-28',
  'mia.harris@mavenhighschool.com'),
 (14,
  'Noah Scott',
  12,
  None,
  'No',
  '2006-10-15',
  'noah.scott@mavenparkdistrict.com'),
 (15,
  'Olivia Adams',
  9,
  3.7,
  'Yes',
  '2009-12-11',
  'olivia.adams@mavenhighschool.com'),
 (16,
  'Peter Park',
  12,
  2.9,
  'Yes',
  '2006-02-11',
  'peter.park@mavenhighschool.com')]

### Running SQL commands with pandas

Just like there are functions to read data from CSV, JSON, EXCEL, there is a function that takes a query and a connection to a database and reads the content:

In [14]:
results_df = pd.read_sql_query(query, conn)
results_df

,id,student_name,grade_level,gpa,school_lunch,birthday,email
0,1,Abby Johnson,10,3.1,Yes,2008-05-14,abby.johnson@mavenhighschool.com
1,2,Bob Smith,11,3.1,No,2007-09-30,bob.smith@mavenhighschool.com
2,3,Catherine Davis,12,3.6,Yes,2006-11-21,catherine.davis@mavenhighschool.com
3,4,Daniel Brown,9,3.5,Yes,2009-03-10,daniel.brown@mavenhighschool.com
4,5,Eva Martinez,10,2.7,No,2008-02-05,eva.martinez@mavenhighschool.com
5,6,Frank Wilson,11,3.2,No,2007-07-17,frank.wilson@mavenhighschool.com
6,7,Grace Lee,12,3.0,Yes,2006-12-02,grace.lee@mavenhighschool.com
7,8,Henry Taylor,9,3.0,Yes,2009-06-08,henry.taylor@mavenhighschool.com
8,9,Isabella Moore,10,2.8,Yes,2008-01-19,isabella.moore@mavenhighschool.com
9,10,Jack Thompson,11,2.9,Yes,2007-04-25,jack.thompson@mavenhighschool.com
10,11,Karen White,9,3.4,No,2009-09-10,karen.white@mavenhighschool.com
11,12,Liam Green,10,4.0,Yes,2008-08-03,liam.green@mavenhighschool.com
12,13,Mia Harris,11,3.0,No,2007-02-28,mia.harris@mavenhighschool.com
13,14,Noah Scott,12,NaN,No,2006-10-15,noah.scott@mavenparkdistrict.com
14,15,Olivia Adams,9,3.7,Yes,2009-12-11,olivia.adams@mavenhighschool.com
15,16,Peter Park,12,2.9,Yes,2006-02-11,peter.park@mavenhighschool.com

<a id="sec3"></a>
## 3. The `SELECT ... FROM` command

Most of the time we don't want all the data, we only want a few colums. In that case we specify queries such as:

```
SELECT
    student_name,
    gpa
FROM
    students;
```

In pandas, this is equivalent to:

```students_df[['student_name', 'gpa']]```

In [15]:
students_df[['student_name', 'gpa']]

       student_name  gpa
id
1      Abby Johnson  3.1
2         Bob Smith  3.1
3   Catherine Davis  3.6
4      Daniel Brown  3.5
5      Eva Martinez  2.7
6      Frank Wilson  3.2
7         Grace Lee  3.0
8      Henry Taylor  3.0
9    Isabella Moore  2.8
10    Jack Thompson  2.9
11      Karen White  3.4
12       Liam Green  4.0
13       Mia Harris  3.0
14       Noah Scott  NaN
15     Olivia Adams  3.7
16       Peter Park  2.9

Now let's do the same with sqlite3:

In [16]:
query = "SELECT student_name, gpa from students"
cursor.execute(query) 
cursor.fetchall()

[('Abby Johnson', 3.1),
 ('Bob Smith', 3.1),
 ('Catherine Davis', 3.6),
 ('Daniel Brown', 3.5),
 ('Eva Martinez', 2.7),
 ('Frank Wilson', 3.2),
 ('Grace Lee', 3.0),
 ('Henry Taylor', 3.0),
 ('Isabella Moore', 2.8),
 ('Jack Thompson', 2.9),
 ('Karen White', 3.4),
 ('Liam Green', 4.0),
 ('Mia Harris', 3.0),
 ('Noah Scott', None),
 ('Olivia Adams', 3.7),
 ('Peter Park', 2.9)]

And then again through pandas. **Note:** Because we already have a dataframe, this is redundant, but we are practicing for situation when you have access to a big database, and not the original CSVs.

In [17]:
pd.read_sql_query(query, conn)

       student_name  gpa
0      Abby Johnson  3.1
1         Bob Smith  3.1
2   Catherine Davis  3.6
3      Daniel Brown  3.5
4      Eva Martinez  2.7
5      Frank Wilson  3.2
6         Grace Lee  3.0
7      Henry Taylor  3.0
8    Isabella Moore  2.8
9     Jack Thompson  2.9
10      Karen White  3.4
11       Liam Green  4.0
12       Mia Harris  3.0
13       Noah Scott  NaN
14     Olivia Adams  3.7
15       Peter Park  2.9

**Task for you:** Write and execute a query that selects the columns student_name, birthday, and email.

In [18]:
query = "SELECT student_name, birthday, email from students"
cursor.execute(query) 
cursor.fetchall()

[('Abby Johnson', '2008-05-14', 'abby.johnson@mavenhighschool.com'),
 ('Bob Smith', '2007-09-30', 'bob.smith@mavenhighschool.com'),
 ('Catherine Davis', '2006-11-21', 'catherine.davis@mavenhighschool.com'),
 ('Daniel Brown', '2009-03-10', 'daniel.brown@mavenhighschool.com'),
 ('Eva Martinez', '2008-02-05', 'eva.martinez@mavenhighschool.com'),
 ('Frank Wilson', '2007-07-17', 'frank.wilson@mavenhighschool.com'),
 ('Grace Lee', '2006-12-02', 'grace.lee@mavenhighschool.com'),
 ('Henry Taylor', '2009-06-08', 'henry.taylor@mavenhighschool.com'),
 ('Isabella Moore', '2008-01-19', 'isabella.moore@mavenhighschool.com'),
 ('Jack Thompson', '2007-04-25', 'jack.thompson@mavenhighschool.com'),
 ('Karen White', '2009-09-10', 'karen.white@mavenhighschool.com'),
 ('Liam Green', '2008-08-03', 'liam.green@mavenhighschool.com'),
 ('Mia Harris', '2007-02-28', 'mia.harris@mavenhighschool.com'),
 ('Noah Scott', '2006-10-15', 'noah.scott@mavenparkdistrict.com'),
 ('Olivia Adams', '2009-12-11', 'olivia.adams@mavenhighschool.com'),
 ('Peter Park', '2006-02-11', 'peter.park@mavenhighschool.com')]

<a id="sec4"></a>
## 4. The `SELECT ... FROM ... WHERE` command

This command allows us to do filtering of a table based on the values of the columns. Here is the SQL command:

```
SELECT
    *
FROM
    students
WHERE
    school_lunch = 'Yes';
```

In pandas this is equivlent to: 

```
students_df[students_df['school_lunch'] == 'Yes']
```

In [19]:
students_df[students_df['school_lunch'] == 'Yes']

,student_name,grade_level,gpa,school_lunch,birthday,email
id,,,,,,
1,Abby Johnson,10,3.1,Yes,5/14/08,abby.johnson@mavenhighschool.com
3,Catherine Davis,12,3.6,Yes,11/21/06,catherine.davis@mavenhighschool.com
4,Daniel Brown,9,3.5,Yes,3/10/09,daniel.brown@mavenhighschool.com
7,Grace Lee,12,3.0,Yes,12/2/06,grace.lee@mavenhighschool.com
8,Henry Taylor,9,3.0,Yes,6/8/09,henry.taylor@mavenhighschool.com
9,Isabella Moore,10,2.8,Yes,1/19/08,isabella.moore@mavenhighschool.com
10,Jack Thompson,11,2.9,Yes,4/25/07,jack.thompson@mavenhighschool.com
12,Liam Green,10,4.0,Yes,8/3/08,liam.green@mavenhighschool.com
15,Olivia Adams,9,3.7,Yes,12/11/09,olivia.adams@mavenhighschool.com
16,Peter Park,12,2.9,Yes,2/11/06,peter.park@mavenhighschool.com

Similarly as above we can run this in sqlite3:

In [20]:
query = "SELECT * from students WHERE school_lunch = 'Yes'"
cursor.execute(query)
cursor.fetchone() # only show me the first line

(1,
 'Abby Johnson',
 10,
 3.1,
 'Yes',
 '2008-05-14',
 'abby.johnson@mavenhighschool.com')

**Task for you:** Filter the table students based on two criteria: school_lunch is "Yes" and the gpa is > than 3.3.

In [22]:
# write the pandas code for filtering
students_df[(students_df['school_lunch']=='Yes') & (students_df['gpa']>3.3)]

,student_name,grade_level,gpa,school_lunch,birthday,email
id,,,,,,
3,Catherine Davis,12,3.6,Yes,11/21/06,catherine.davis@mavenhighschool.com
4,Daniel Brown,9,3.5,Yes,3/10/09,daniel.brown@mavenhighschool.com
12,Liam Green,10,4.0,Yes,8/3/08,liam.green@mavenhighschool.com
15,Olivia Adams,9,3.7,Yes,12/11/09,olivia.adams@mavenhighschool.com

In [24]:
# write the SQL query and then execute, refer to video for syntax
query = "SELECT * from students WHERE school_lunch = 'Yes' AND gpa > 3.3"
cursor.execute(query)
cursor.fetchall() # only show me the first line

[(3,
  'Catherine Davis',
  12,
  3.6,
  'Yes',
  '2006-11-21',
  'catherine.davis@mavenhighschool.com'),
 (4,
  'Daniel Brown',
  9,
  3.5,
  'Yes',
  '2009-03-10',
  'daniel.brown@mavenhighschool.com'),
 (12,
  'Liam Green',
  10,
  4.0,
  'Yes',
  '2008-08-03',
  'liam.green@mavenhighschool.com'),
 (15,
  'Olivia Adams',
  9,
  3.7,
  'Yes',
  '2009-12-11',
  'olivia.adams@mavenhighschool.com')]

## 5. Sorting with `ORDER BY`

The SQL query in this occasion is:

```
SELECT
    *
FROM
    students
ORDER BY
    gpa ASC;
```

This will sort the data in the ascending order:

In [25]:
query = "SELECT * FROM students ORDER BY gpa ASC"
cursor.execute(query)
cursor.fetchall()

[(14,
  'Noah Scott',
  12,
  None,
  'No',
  '2006-10-15',
  'noah.scott@mavenparkdistrict.com'),
 (5,
  'Eva Martinez',
  10,
  2.7,
  'No',
  '2008-02-05',
  'eva.martinez@mavenhighschool.com'),
 (9,
  'Isabella Moore',
  10,
  2.8,
  'Yes',
  '2008-01-19',
  'isabella.moore@mavenhighschool.com'),
 (10,
  'Jack Thompson',
  11,
  2.9,
  'Yes',
  '2007-04-25',
  'jack.thompson@mavenhighschool.com'),
 (16,
  'Peter Park',
  12,
  2.9,
  'Yes',
  '2006-02-11',
  'peter.park@mavenhighschool.com'),
 (7,
  'Grace Lee',
  12,
  3.0,
  'Yes',
  '2006-12-02',
  'grace.lee@mavenhighschool.com'),
 (8,
  'Henry Taylor',
  9,
  3.0,
  'Yes',
  '2009-06-08',
  'henry.taylor@mavenhighschool.com'),
 (13,
  'Mia Harris',
  11,
  3.0,
  'No',
  '2007-02-28',
  'mia.harris@mavenhighschool.com'),
 (1,
  'Abby Johnson',
  10,
  3.1,
  'Yes',
  '2008-05-14',
  'abby.johnson@mavenhighschool.com'),
 (2,
  'Bob Smith',
  11,
  3.1,
  'No',
  '2007-09-30',
  'bob.smith@mavenhighschool.com'),
 (6,
  'Frank Wilson',
  11,
  3.2,
  'No',
  '2007-07-17',
  'frank.wilson@mavenhighschool.com'),
 (11,
  'Karen White',
  9,
  3.4,
  'No',
  '2009-09-10',
  'karen.white@mavenhighschool.com'),
 (4,
  'Daniel Brown',
  9,
  3.5,
  'Yes',
  '2009-03-10',
  'daniel.brown@mavenhighschool.com'),
 (3,
  'Catherine Davis',
  12,
  3.6,
  'Yes',
  '2006-11-21',
  'catherine.davis@mavenhighschool.com'),
 (15,
  'Olivia Adams',
  9,
  3.7,
  'Yes',
  '2009-12-11',
  'olivia.adams@mavenhighschool.com'),
 (12,
  'Liam Green',
  10,
  4.0,
  'Yes',
  '2008-08-03',
  'liam.green@mavenhighschool.com')]

We can use DESC for the descending order:

In [26]:
query = "SELECT * FROM students ORDER BY gpa DESC"
cursor.execute(query)
cursor.fetchall()

[(12,
  'Liam Green',
  10,
  4.0,
  'Yes',
  '2008-08-03',
  'liam.green@mavenhighschool.com'),
 (15,
  'Olivia Adams',
  9,
  3.7,
  'Yes',
  '2009-12-11',
  'olivia.adams@mavenhighschool.com'),
 (3,
  'Catherine Davis',
  12,
  3.6,
  'Yes',
  '2006-11-21',
  'catherine.davis@mavenhighschool.com'),
 (4,
  'Daniel Brown',
  9,
  3.5,
  'Yes',
  '2009-03-10',
  'daniel.brown@mavenhighschool.com'),
 (11,
  'Karen White',
  9,
  3.4,
  'No',
  '2009-09-10',
  'karen.white@mavenhighschool.com'),
 (6,
  'Frank Wilson',
  11,
  3.2,
  'No',
  '2007-07-17',
  'frank.wilson@mavenhighschool.com'),
 (1,
  'Abby Johnson',
  10,
  3.1,
  'Yes',
  '2008-05-14',
  'abby.johnson@mavenhighschool.com'),
 (2,
  'Bob Smith',
  11,
  3.1,
  'No',
  '2007-09-30',
  'bob.smith@mavenhighschool.com'),
 (7,
  'Grace Lee',
  12,
  3.0,
  'Yes',
  '2006-12-02',
  'grace.lee@mavenhighschool.com'),
 (8,
  'Henry Taylor',
  9,
  3.0,
  'Yes',
  '2009-06-08',
  'henry.taylor@mavenhighschool.com'),
 (13,
  'Mia Harris',
  11,
  3.0,
  'No',
  '2007-02-28',
  'mia.harris@mavenhighschool.com'),
 (10,
  'Jack Thompson',
  11,
  2.9,
  'Yes',
  '2007-04-25',
  'jack.thompson@mavenhighschool.com'),
 (16,
  'Peter Park',
  12,
  2.9,
  'Yes',
  '2006-02-11',
  'peter.park@mavenhighschool.com'),
 (9,
  'Isabella Moore',
  10,
  2.8,
  'Yes',
  '2008-01-19',
  'isabella.moore@mavenhighschool.com'),
 (5,
  'Eva Martinez',
  10,
  2.7,
  'No',
  '2008-02-05',
  'eva.martinez@mavenhighschool.com'),
 (14,
  'Noah Scott',
  12,
  None,
  'No',
  '2006-10-15',
  'noah.scott@mavenparkdistrict.com')]

**Your Task:** Write pandas code to sort the dataframe first in ascending and then in decscending order.

In [29]:
students_df.sort_values(by='gpa', ascending=True)

,student_name,grade_level,gpa,school_lunch,birthday,email
id,,,,,,
5,Eva Martinez,10,2.7,No,2/5/08,eva.martinez@mavenhighschool.com
9,Isabella Moore,10,2.8,Yes,1/19/08,isabella.moore@mavenhighschool.com
10,Jack Thompson,11,2.9,Yes,4/25/07,jack.thompson@mavenhighschool.com
16,Peter Park,12,2.9,Yes,2/11/06,peter.park@mavenhighschool.com
7,Grace Lee,12,3.0,Yes,12/2/06,grace.lee@mavenhighschool.com
8,Henry Taylor,9,3.0,Yes,6/8/09,henry.taylor@mavenhighschool.com
13,Mia Harris,11,3.0,No,2/28/07,mia.harris@mavenhighschool.com
1,Abby Johnson,10,3.1,Yes,5/14/08,abby.johnson@mavenhighschool.com
2,Bob Smith,11,3.1,No,9/30/07,bob.smith@mavenhighschool.com
6,Frank Wilson,11,3.2,No,7/17/07,frank.wilson@mavenhighschool.com
11,Karen White,9,3.4,No,9/10/09,karen.white@mavenhighschool.com
4,Daniel Brown,9,3.5,Yes,3/10/09,daniel.brown@mavenhighschool.com
3,Catherine Davis,12,3.6,Yes,11/21/06,catherine.davis@mavenhighschool.com
15,Olivia Adams,9,3.7,Yes,12/11/09,olivia.adams@mavenhighschool.com
12,Liam Green,10,4.0,Yes,8/3/08,liam.green@mavenhighschool.com
14,Noah Scott,12,NaN,No,10/15/06,noah.scott@mavenparkdistrict.com

In [30]:
students_df.sort_values(by='gpa', ascending=False)

,student_name,grade_level,gpa,school_lunch,birthday,email
id,,,,,,
12,Liam Green,10,4.0,Yes,8/3/08,liam.green@mavenhighschool.com
15,Olivia Adams,9,3.7,Yes,12/11/09,olivia.adams@mavenhighschool.com
3,Catherine Davis,12,3.6,Yes,11/21/06,catherine.davis@mavenhighschool.com
4,Daniel Brown,9,3.5,Yes,3/10/09,daniel.brown@mavenhighschool.com
11,Karen White,9,3.4,No,9/10/09,karen.white@mavenhighschool.com
6,Frank Wilson,11,3.2,No,7/17/07,frank.wilson@mavenhighschool.com
1,Abby Johnson,10,3.1,Yes,5/14/08,abby.johnson@mavenhighschool.com
2,Bob Smith,11,3.1,No,9/30/07,bob.smith@mavenhighschool.com
7,Grace Lee,12,3.0,Yes,12/2/06,grace.lee@mavenhighschool.com
8,Henry Taylor,9,3.0,Yes,6/8/09,henry.taylor@mavenhighschool.com
13,Mia Harris,11,3.0,No,2/28/07,mia.harris@mavenhighschool.com
10,Jack Thompson,11,2.9,Yes,4/25/07,jack.thompson@mavenhighschool.com
16,Peter Park,12,2.9,Yes,2/11/06,peter.park@mavenhighschool.com
9,Isabella Moore,10,2.8,Yes,1/19/08,isabella.moore@mavenhighschool.com
5,Eva Martinez,10,2.7,No,2/5/08,eva.martinez@mavenhighschool.com
14,Noah Scott,12,NaN,No,10/15/06,noah.scott@mavenparkdistrict.com

<a id="sec6"></a>
## 6. Combine all commands

Now that you saw the commands SELECT ... FROM, WHERE, and ORDER BY, write code both in SQL and in pandas to sort in descending orders students with no school lunch and gpa greater than 3.0. You should be able to find 3 such students. Fee free to write the Pandas one first, if it helps you get a sense of what you are doing. (The SQL solution is in the video.)

In [33]:
# SQL solution
query = "SELECT * FROM students WHERE school_lunch = 'No' AND gpa > 3.0 ORDER BY gpa DESC"

cursor.execute(query)
cursor.fetchall()

[(11,
  'Karen White',
  9,
  3.4,
  'No',
  '2009-09-10',
  'karen.white@mavenhighschool.com'),
 (6,
  'Frank Wilson',
  11,
  3.2,
  'No',
  '2007-07-17',
  'frank.wilson@mavenhighschool.com'),
 (2,
  'Bob Smith',
  11,
  3.1,
  'No',
  '2007-09-30',
  'bob.smith@mavenhighschool.com')]

In [31]:
# Pandas solution
students_df[(students_df['school_lunch']=='No') & (students_df['gpa']>3)].sort_values(by='gpa',ascending=False)

,student_name,grade_level,gpa,school_lunch,birthday,email
id,,,,,,
11,Karen White,9,3.4,No,9/10/09,karen.white@mavenhighschool.com
6,Frank Wilson,11,3.2,No,7/17/07,frank.wilson@mavenhighschool.com
2,Bob Smith,11,3.1,No,9/30/07,bob.smith@mavenhighschool.com

<a id="sec7"></a>
## 7. The `GROUP BY` command

Suppose that now we want to calculate the average GPA by grade level. This is something that we learned to do with the `groupby` function in Pandas, but Pandas has borrowed that from SQL databases.

This is how we'll write this in SQL:

```
SELECT
    grade_level,
    AVG(gpa) AS average_gpa
FROM
    students
GROUP BY
    grade_level;
```

In [34]:
query = "SELECT grade_level, avg(gpa) AS average_gpa FROM students GROUP BY grade_level"
cursor.execute(query)
cursor.fetchall()

[(9, 3.4), (10, 3.15), (11, 3.05), (12, 3.1666666666666665)]

**Task for you:** Solve the same problem but now using pandas's groupby function.

In [35]:
students_df.groupby('grade_level')['gpa'].mean()

grade_level
9     3.400000
10    3.150000
11    3.050000
12    3.166667
Name: gpa, dtype: float64

<a id="sec8"></a>
## 8. Filtering aggregated data with HAVING

Once we have grouped data by a certain criteria (for example the average gpa), we might want to further filter the data to focus only on a subset of it. For example, we might want to: **Filter groups where average GPA is below 3.3**

This is done by this SQL query:

```
SELECT
    grade_level,
    AVG(gpa) AS average_gpa
FROM
    students
GROUP BY
    grade_level
HAVING
    average_gpa < 3.3;
```

In [36]:
query = "SELECT grade_level, AVG(gpa) AS average_gpa FROM students GROUP BY grade_level HAVING average_gpa < 3.3;"
cursor.execute(query)
cursor.fetchall()

[(10, 3.15), (11, 3.05), (12, 3.1666666666666665)]

**Task for you:** Repeat the same task but now with pandas. **Hint:** First create a new dataframe by using .reset_index with the name parameter to name the average_gpa as a column. Then, it will be easy to filter by the values of this column.

In [42]:
new_df = students_df.groupby('grade_level')['gpa'].mean().reset_index().rename(columns={'gpa': 'average_gpa'}) 
new_df[new_df['average_gpa'] < 3.4]

   grade_level  average_gpa
1           10     3.150000
2           11     3.050000
3           12     3.166667

<a id="sec9"></a>
## 9. Utility Keywords

Here are three useful keywords in SQL for some useful tasks. Remember to watch the video for explanations on them.

* LIMIT
* COUNT
* DISTINCT

Your task will be to find the pandas equivalents for each of them once you have executed the SQL code.

In [43]:
query = """
SELECT
    *
FROM
    students
LIMIT 5;"""
cursor.execute(query)
cursor.fetchall()

[(1,
  'Abby Johnson',
  10,
  3.1,
  'Yes',
  '2008-05-14',
  'abby.johnson@mavenhighschool.com'),
 (2,
  'Bob Smith',
  11,
  3.1,
  'No',
  '2007-09-30',
  'bob.smith@mavenhighschool.com'),
 (3,
  'Catherine Davis',
  12,
  3.6,
  'Yes',
  '2006-11-21',
  'catherine.davis@mavenhighschool.com'),
 (4,
  'Daniel Brown',
  9,
  3.5,
  'Yes',
  '2009-03-10',
  'daniel.brown@mavenhighschool.com'),
 (5,
  'Eva Martinez',
  10,
  2.7,
  'No',
  '2008-02-05',
  'eva.martinez@mavenhighschool.com')]

**Task for you:** Write the pandas equivalent. (It's very simple and we use it all the time.)

In [44]:
students_df.head()

,student_name,grade_level,gpa,school_lunch,birthday,email
id,,,,,,
1,Abby Johnson,10,3.1,Yes,5/14/08,abby.johnson@mavenhighschool.com
2,Bob Smith,11,3.1,No,9/30/07,bob.smith@mavenhighschool.com
3,Catherine Davis,12,3.6,Yes,11/21/06,catherine.davis@mavenhighschool.com
4,Daniel Brown,9,3.5,Yes,3/10/09,daniel.brown@mavenhighschool.com
5,Eva Martinez,10,2.7,No,2/5/08,eva.martinez@mavenhighschool.com

In [45]:
query = """
SELECT
    COUNT(*)
FROM
    students;"""
cursor.execute(query)
cursor.fetchall()

[(16,)]

**Task for you:** How can we get the number of rows for a dataframe in pandas?

In [46]:
students_df.shape[0]

16

In [47]:
query = """
SELECT DISTINCT
    GPA
FROM
    students
ORDER BY
    GPA DESC;"""

cursor.execute(query)
cursor.fetchall()

[(4.0,),
 (3.7,),
 (3.6,),
 (3.5,),
 (3.4,),
 (3.2,),
 (3.1,),
 (3.0,),
 (2.9,),
 (2.8,),
 (2.7,),
 (None,)]

**Task for you:** Find a way to get the same distinct values in pandas (there are different ways to do this).

In [48]:
students_df['gpa'].unique()

array([3.1, 3.6, 3.5, 2.7, 3.2, 3. , 2.8, 2.9, 3.4, 4. , nan, 3.7])

<a id="sec10"></a>
## 10. Combining Tables

Combining tables is done through the so-called "left join". In pandas this is accomplished by using `.merge`. Let's see both cases. Again, first rewatch the video before running this snippet.

In [ ]:
query = """
SELECT
    s.student_name,
    sg.class_name,
    sg.final_grade
FROM
    students AS s
LEFT JOIN
    student_grades AS sg
ON
    s.id = sg.student_id;
"""
cursor.execute(query)
cursor.fetchall()

[('Abby Johnson', 'Chemistry', 94),
 ('Bob Smith', 'Chemistry', 87),
 ('Catherine Davis', 'Calculus', 98),
 ('Daniel Brown', 'Algebra', 85),
 ('Eva Martinez', 'Chemistry', 74),
 ('Frank Wilson', 'Chemistry', 98),
 ('Grace Lee', 'Calculus', 86),
 ('Henry Taylor', 'Algebra', 76),
 ('Isabella Moore', 'Chemistry', 76),
 ('Jack Thompson', 'Physical Education', 85),
 ('Karen White', 'Algebra', 90),
 ('Liam Green', 'Physical Education', 95),
 ('Mia Harris', 'Physical Education', 90),
 ('Noah Scott', None, None),
 ('Olivia Adams', 'Algebra', 97),
 ('Peter Park', 'Calculus', 71)]

Pandas solution:

In [50]:
merged_df = pd.merge(
    students_df,
    student_grades_df,
    how='left',           # Equivalent to LEFT JOIN
    left_on='id',         # Key from the left dataframe (students_df)
    right_on='student_id' # Key from the right dataframe (student_grades_df)
)

merged_df[['student_name', 'class_name', 'final_grade']]

    student_name          class_name  final_grade
0   Abby Johnson            Geometry         93.0
1   Abby Johnson           Chemistry         94.0
2   Abby Johnson             English         82.0
3   Abby Johnson  Physical Education         85.0
4      Bob Smith          Statistics         88.0
..           ...                 ...          ...
56  Olivia Adams  Physical Education         95.0
57    Peter Park            Calculus         71.0
58    Peter Park             Physics         74.0
59    Peter Park       World History         86.0
60    Peter Park      Senior Seminar         95.0

[61 rows x 3 columns]

<a id="sec11"></a>
## 11. Practice Problems

Try your best to solve these problems both with SQL and pandas.

**Problem 1:** Find the names and GPAs of all students in grade 10 who have a GPA above 3.0, sorted by their GPA from highest to lowest.

In [53]:
# SQL
query = """
SELECT
   student_name, gpa
FROM
    students 
WHERE
    grade_level = 10 AND gpa > 3.0
ORDER BY 
    gpa DESC
"""

cursor.execute(query)
cursor.fetchall()

[('Liam Green', 4.0), ('Abby Johnson', 3.1)]

In [57]:
# pandas
students_df[(students_df['grade_level']==10) & (students_df['gpa']>3)][['student_name', 'gpa']].sort_values(by='gpa', ascending=False)

    student_name  gpa
id
12    Liam Green  4.0
1   Abby Johnson  3.1

**Problem 2:** Determine how many total classes each student has recorded in the `student_grades` table. Include the student's name in the final output.

In [62]:
merged_df.head()

,student_name,grade_level,gpa,school_lunch,birthday,email,semester_id,class_id,department,class_name,student_id,final_grade
0,Abby Johnson,10,3.1,Yes,5/14/08,abby.johnson@mavenhighschool.com,SPR_2024,102.0,Math,Geometry,1.0,93.0
1,Abby Johnson,10,3.1,Yes,5/14/08,abby.johnson@mavenhighschool.com,SPR_2024,202.0,Science,Chemistry,1.0,94.0
2,Abby Johnson,10,3.1,Yes,5/14/08,abby.johnson@mavenhighschool.com,SPR_2024,301.0,Humanities,English,1.0,82.0
3,Abby Johnson,10,3.1,Yes,5/14/08,abby.johnson@mavenhighschool.com,SPR_2024,401.0,General,Physical Education,1.0,85.0
4,Bob Smith,11,3.1,No,9/30/07,bob.smith@mavenhighschool.com,SPR_2024,103.0,Math,Statistics,2.0,88.0

In [74]:
# SQL
query = """
SELECT
    s.student_name,
    COUNT(DISTINCT sg.class_name) AS total_classes
FROM
    students AS s
LEFT JOIN
    student_grades AS sg
ON
    s.id = sg.student_id
GROUP BY
    s.id
"""
cursor.execute(query)
cursor.fetchall()

[('Abby Johnson', 4),
 ('Bob Smith', 4),
 ('Catherine Davis', 4),
 ('Daniel Brown', 4),
 ('Eva Martinez', 4),
 ('Frank Wilson', 4),
 ('Grace Lee', 4),
 ('Henry Taylor', 4),
 ('Isabella Moore', 4),
 ('Jack Thompson', 4),
 ('Karen White', 4),
 ('Liam Green', 4),
 ('Mia Harris', 4),
 ('Noah Scott', 0),
 ('Olivia Adams', 4),
 ('Peter Park', 4)]

In [63]:
# pandas
merged_df.groupby('student_name')['class_name'].nunique()

student_name
Abby Johnson       4
Bob Smith          4
Catherine Davis    4
Daniel Brown       4
Eva Martinez       4
Frank Wilson       4
Grace Lee          4
Henry Taylor       4
Isabella Moore     4
Jack Thompson      4
Karen White        4
Liam Green         4
Mia Harris         4
Noah Scott         0
Olivia Adams       4
Peter Park         4
Name: class_name, dtype: int64

# TASK 3B

First, let's connect to our simple database.

In [13]:
import sqlite3

db_file = "/Users/crystalzhao/Desktop/~WELLESLEY~/FALL_26/CS 315/week8-tues/simple_netflix.db"

conn = sqlite3.connect(db_file) # you are connected to the database
cursor = conn.cursor() # you have appointed a "helper" that will perform SQL commands for you
cursor

I had to copy in the full path because otherwise this would only look within my current directory of sql vs. pandas.

The instructions were just to explore the data, so let's try these:    
- utility keywords
- select from where
- group by -> having

### Overview

In [14]:
query = """
SELECT
    *
FROM
    simple
LIMIT 5;"""
cursor.execute(query)
cursor.fetchall()

[(1, 'AR', '2026-10-04', 1, 'Films', 'UNABOMBER'),
 (2, 'AR', '2026-10-04', 2, 'Films', 'The Equalizer 3'),
 (3, 'AR', '2026-10-04', 3, 'Films', 'The Substance'),
 (4,
  'AR',
  '2026-10-04',
  4,
  'Films',
  'Demon Slayer: Kimetsu no Yaiba Infinity Castle I'),
 (5, 'AR', '2026-10-04', 5, 'Films', 'What a Father!')]

How many rows are there?

In [15]:
query = """
SELECT
    COUNT(*)
FROM
    simple;"""
cursor.execute(query)
cursor.fetchall()

[(512200,)]

### SELECT FROM WHERE

I want to explore all weeks with top 1 TV shows in the US.

In [28]:
# SQL solution
query = "SELECT week, show_title FROM simple WHERE category == 'TV' AND country == 'US' AND rank == 1"

cursor.execute(query)
cursor.fetchall()

[('2026-10-04', 'A Different World'),
 ('2026-09-27', 'Monster: The Lizzie Borden Story'),
 ('2026-09-20', 'Monster: The Lizzie Borden Story'),
 ('2026-09-13', "Death of the Pastor's Wife"),
 ('2026-09-06', "Death of the Pastor's Wife"),
 ('2026-08-30', "Death of the Pastor's Wife"),
 ('2026-08-23', 'Outer Banks'),
 ('2026-08-16', 'My Life With the Walter Boys'),
 ('2026-08-09', 'The Idaho Murders: College Nightmare'),
 ('2026-08-02', 'The Idaho Murders: College Nightmare'),
 ('2026-07-26', 'The Hawk'),
 ('2026-07-19', 'The Hawk'),
 ('2026-07-12', 'Worst Neighbor Ever'),
 ('2026-07-05', 'Worst Neighbor Ever'),
 ('2026-06-28', 'I Will Find You'),
 ('2026-06-21', 'I Will Find You'),
 ('2026-06-14', 'Michael Jackson: The Verdict'),
 ('2026-06-07', 'Michael Jackson: The Verdict'),
 ('2026-05-31', 'The Boroughs'),
 ('2026-05-24', 'Nemesis'),
 ('2026-05-17', 'The Roast of Kevin Hart'),
 ('2026-05-10', 'Worst Ex Ever'),
 ('2026-05-03', 'Should I Marry A Murderer?'),
 ('2026-04-26', 'Unchosen'),
 ('2026-04-19', 'Trust Me: The False Prophet'),
 ('2026-04-12', 'Trust Me: The False Prophet'),
 ('2026-04-05', 'XO, Kitty'),
 ('2026-03-29', 'Beauty in Black'),
 ('2026-03-22', 'Virgin River'),
 ('2026-03-15', 'The Reunion'),
 ('2026-03-08', 'Bridgerton'),
 ('2026-03-01', 'Bridgerton'),
 ('2026-02-22', "Reality Check: Inside America's Next Top Model"),
 ('2026-02-15', 'Katt Williams: The Last Report'),
 ('2026-02-08', 'Bridgerton'),
 ('2026-02-01', 'Bridgerton'),
 ('2026-01-25', 'HIS & HERS'),
 ('2026-01-18', 'HIS & HERS'),
 ('2026-01-11', 'HIS & HERS'),
 ('2026-01-04', 'Stranger Things'),
 ('2025-12-28', 'Stranger Things'),
 ('2025-12-21', 'Jake Paul vs. Anthony Joshua'),
 ('2025-12-14', 'Sean Combs: The Reckoning'),
 ('2025-12-07', 'Sean Combs: The Reckoning'),
 ('2025-11-30', 'Stranger Things'),
 ('2025-11-23', 'The Beast in Me'),
 ('2025-11-16', 'The Beast in Me'),
 ('2025-11-09', 'Leanne Morgan: Unspeakable Things'),
 ('2025-11-02', 'Nobody Wants This'),
 ('2025-10-26', 'Nobody Wants This'),
 ('2025-10-19', 'Monster: The Ed Gein Story'),
 ('2025-10-12', 'Monster: The Ed Gein Story'),
 ('2025-10-05', 'Wayward'),
 ('2025-09-28', 'Black Rabbit'),
 ('2025-09-21', 'Black Rabbit'),
 ('2025-09-14', 'Canelo Álvarez vs. Terence Crawford'),
 ('2025-09-07', 'Wednesday'),
 ('2025-08-31', 'Katrina: Come Hell and High Water'),
 ('2025-08-24', 'Fit for TV: The Reality of the Biggest Loser'),
 ('2025-08-17', 'Wednesday'),
 ('2025-08-10', 'Wednesday'),
 ('2025-08-03', 'The Hunting Wives'),
 ('2025-07-27', 'UNTAMED'),
 ('2025-07-20', 'UNTAMED'),
 ('2025-07-13', "Sullivan's Crossing"),
 ('2025-07-06', 'Squid Game'),
 ('2025-06-29', 'Squid Game'),
 ('2025-06-22', 'The Waterfront'),
 ('2025-06-15', 'Ginny & Georgia'),
 ('2025-06-08', 'Ginny & Georgia'),
 ('2025-06-01', 'Sirens'),
 ('2025-05-25', 'Sirens'),
 ('2025-05-18', 'American Manhunt: Osama bin Laden'),
 ('2025-05-11', 'The Four Seasons'),
 ('2025-05-04', 'The Four Seasons'),
 ('2025-04-27', 'Ransom Canyon'),
 ('2025-04-20', 'Ransom Canyon'),
 ('2025-04-13', 'Bad Influence: The Dark Side of Kidfluencing'),
 ('2025-04-06', 'Gone Girls: The Long Island Serial Killer'),
 ('2025-03-30', 'Adolescence'),
 ('2025-03-23', 'Adolescence'),
 ('2025-03-16', 'Adolescence'),
 ('2025-03-09', 'Running Point'),
 ('2025-03-02', 'American Murder: Gabby Petito'),
 ('2025-02-23', 'American Murder: Gabby Petito'),
 ('2025-02-16', 'Surviving Black Hawk Down'),
 ('2025-02-09', 'American Manhunt: O.J. Simpson'),
 ('2025-02-02', 'The Night Agent'),
 ('2025-01-26', 'The Night Agent'),
 ('2025-01-19', 'American Primeval'),
 ('2025-01-12', 'Squid Game'),
 ('2025-01-05', 'Squid Game'),
 ('2024-12-29', 'Christmas Gameday: Ravens vs. Texans'),
 ('2024-12-22', 'La Palma'),
 ('2024-12-15', 'Jamie Foxx: What Had Happened Was...'),
 ('2024-12-08', 'The Madness'),
 ('2024-12-01', 'Cold Case: Who Killed JonBenét Ramsey'),
 ('2024-11-24', 'A Man on the Inside'),
 ('2024-11-17', 'Jake Paul vs. Mike Tyson'),
 ('2024-11-10', 'Outer Banks'),
 ('2024-11-03', 'Beauty in Black'),
 ('2024-10-27', 'This Is the Zodiac Speaking'),
 ('2024-10-20', 'Outer Banks'),
 ('2024-10-13', 'Outer Banks'),
 ('2024-10-06', 'Nobody Wants This'),
 ('2024-09-29', 'Monsters'),
 ('2024-09-22', 'Monsters'),
 ('2024-09-15', 'The Perfect Couple'),
 ('2024-09-08', 'The Perfect Couple'),
 ('2024-09-01', 'Worst Ex Ever'),
 ('2024-08-25', 'American Murder: Laci Peterson'),
 ('2024-08-18', 'American Murder: Laci Peterson'),
 ('2024-08-11', 'The Umbrella Academy'),
 ('2024-08-04', "A Good Girl's Guide to Murder"),
 ('2024-07-28', 'Cobra Kai'),
 ('2024-07-21', 'Cobra Kai'),
 ('2024-07-14', 'The Man with 1000 Kids'),
 ('2024-07-07', 'The Man with 1000 Kids'),
 ('2024-06-30', 'Worst Roommate Ever'),
 ('2024-06-23', 'Bridgerton'),
 ('2024-06-16', 'Bridgerton'),
 ('2024-06-09', 'Dancing for the Devil: The 7M TikTok Cult'),
 ('2024-06-02', 'Dancing for the Devil: The 7M TikTok Cult'),
 ('2024-05-26', 'Bridgerton'),
 ('2024-05-19', 'Bridgerton'),
 ('2024-05-12', 'The Roast of Tom Brady'),
 ('2024-05-05', 'Baby Reindeer'),
 ('2024-04-28', 'Baby Reindeer'),
 ('2024-04-21', 'Baby Reindeer'),
 ('2024-04-14', 'Unlocked: A Jail Experiment'),
 ('2024-04-07', 'Files of the Unexplained'),
 ('2024-03-31', 'Testament: The Story of Moses'),
 ('2024-03-24', 'Homicide'),
 ('2024-03-17', 'The Gentlemen'),
 ('2024-03-10', 'The Program: Cons, Cults and Kidnapping'),
 ('2024-03-03', 'Avatar: The Last Airbender'),
 ('2024-02-25', 'Avatar: The Last Airbender'),
 ('2024-02-18', 'Love Is Blind'),
 ('2024-02-11', 'Griselda'),
 ('2024-02-04', 'Griselda'),
 ('2024-01-28', 'Griselda'),
 ('2024-01-21', 'American Nightmare'),
 ('2024-01-14', 'Fool Me Once'),
 ('2024-01-07', 'Fool Me Once'),
 ('2023-12-31', 'Ricky Gervais: Armageddon'),
 ('2023-12-24', 'My Life With the Walter Boys'),
 ('2023-12-17', 'My Life With the Walter Boys'),
 ('2023-12-10', 'My Life With the Walter Boys'),
 ('2023-12-03', 'Squid Game: The Challenge'),
 ('2023-11-26', 'Squid Game: The Challenge'),
 ('2023-11-19', 'Matt Rife: Natural Selection'),
 ('2023-11-12', 'All the Light We Cannot See'),
 ('2023-11-05', 'All the Light We Cannot See'),
 ('2023-10-29', 'Get Gotti'),
 ('2023-10-22', 'The Fall of the House of Usher'),
 ('2023-10-15', 'The Fall of the House of Usher'),
 ('2023-10-08', 'Beckham'),
 ('2023-10-01', 'Love Is Blind'),
 ('2023-09-24', 'Murdaugh Murders: A Southern Scandal'),
 ('2023-09-17', 'Virgin River'),
 ('2023-09-10', 'Virgin River'),
 ('2023-09-03', 'Who is Erin Carter?'),
 ('2023-08-27', 'Untold: Swamp Kings'),
 ('2023-08-20', 'DEPP V HEARD'),
 ('2023-08-13', 'Painkiller'),
 ('2023-08-06', 'The Lincoln Lawyer'),
 ('2023-07-30', 'Sweet Magnolias'),
 ('2023-07-23', 'Sweet Magnolias'),
 ('2023-07-16', 'The Lincoln Lawyer'),
 ('2023-07-09', 'Tom Segura: Sledgehammer'),
 ('2023-07-02', 'The Witcher'),
 ('2023-06-25', 'Black Mirror'),
 ('2023-06-18', 'Black Mirror'),
 ('2023-06-11', 'Never Have I Ever'),
 ('2023-06-04', 'FUBAR'),
 ('2023-05-28', 'FUBAR'),
 ('2023-05-21', 'Queen Charlotte: A Bridgerton Story'),
 ('2023-05-14', 'Queen Charlotte: A Bridgerton Story'),
 ('2023-05-07', 'Queen Charlotte: A Bridgerton Story'),
 ('2023-04-30', 'The Diplomat'),
 ('2023-04-23', 'Love Is Blind'),
 ('2023-04-16', 'BEEF'),
 ('2023-04-09', 'The Night Agent'),
 ('2023-04-02', 'The Night Agent'),
 ('2023-03-26', 'The Night Agent'),
 ('2023-03-19', 'You'),
 ('2023-03-12', 'You'),
 ('2023-03-05', 'Outer Banks'),
 ('2023-02-26', 'Outer Banks'),
 ('2023-02-19', 'You'),
 ('2023-02-12', 'You'),
 ('2023-02-05', 'New Amsterdam'),
 ('2023-01-29', 'Ginny & Georgia'),
 ('2023-01-22', 'Ginny & Georgia'),
 ('2023-01-15', 'Ginny & Georgia'),
 ('2023-01-08', 'Ginny & Georgia'),
 ('2023-01-01', 'Wednesday'),
 ('2022-12-25', 'The Recruit'),
 ('2022-12-18', 'Wednesday'),
 ('2022-12-11', 'Wednesday'),
 ('2022-12-04', 'Wednesday'),
 ('2022-11-27', 'Wednesday'),
 ('2022-11-20', 'The Crown'),
 ('2022-11-13', 'The Crown'),
 ('2022-11-06', 'Love Is Blind'),
 ('2022-10-30', 'The Watcher'),
 ('2022-10-23', 'The Watcher'),
 ('2022-10-16', 'The Watcher'),
 ('2022-10-09', 'DAHMER'),
 ('2022-10-02', 'DAHMER'),
 ('2022-09-25', 'DAHMER'),
 ('2022-09-18', 'Cobra Kai'),
 ('2022-09-11', 'Cobra Kai'),
 ('2022-09-04', 'Devil in Ohio'),
 ('2022-08-28', 'Echoes'),
 ('2022-08-21', 'The Sandman'),
 ('2022-08-14', 'The Sandman'),
 ('2022-08-07', 'The Sandman'),
 ('2022-07-31', 'Virgin River'),
 ('2022-07-24', 'Virgin River'),
 ('2022-07-17', 'Stranger Things'),
 ('2022-07-10', 'Stranger Things'),
 ('2022-07-03', 'Stranger Things'),
 ('2022-06-26', 'The Umbrella Academy'),
 ('2022-06-19', 'Stranger Things'),
 ('2022-06-12', 'Stranger Things'),
 ('2022-06-05', 'Stranger Things'),
 ('2022-05-29', 'Stranger Things'),
 ('2022-05-22', 'The Lincoln Lawyer'),
 ('2022-05-15', 'Ozark'),
 ('2022-05-08', 'Ozark'),
 ('2022-05-01', 'Ozark'),
 ('2022-04-24', 'Anatomy of a Scandal'),
 ('2022-04-17', 'The Ultimatum: Marry or Move On'),
 ('2022-04-10', 'Bridgerton'),
 ('2022-04-03', 'Bridgerton'),
 ('2022-03-27', 'Bridgerton'),
 ('2022-03-20', 'Good Girls'),
 ('2022-03-13', 'PIECES OF HER'),
 ('2022-03-06', 'Worst Roommate Ever'),
 ('2022-02-27', 'Inventing Anna'),
 ('2022-02-20', 'Inventing Anna'),
 ('2022-02-13', 'Inventing Anna'),
 ('2022-02-06', 'All of Us Are Dead'),
 ('2022-01-30', 'Ozark'),
 ('2022-01-23', 'Ozark'),
 ('2022-01-16', 'Cheer'),
 ('2022-01-09', 'Cobra Kai'),
 ('2022-01-02', 'Cobra Kai'),
 ('2021-12-26', 'The Witcher'),
 ('2021-12-19', 'The Witcher'),
 ('2021-12-12', 'Money Heist'),
 ('2021-12-05', 'True Story'),
 ('2021-11-28', 'True Story'),
 ('2021-11-21', 'Tiger King'),
 ('2021-11-14', 'Narcos: Mexico'),
 ('2021-11-07', 'You'),
 ('2021-10-31', 'You'),
 ('2021-10-24', 'You'),
 ('2021-10-17', 'Squid Game'),
 ('2021-10-10', 'Squid Game'),
 ('2021-10-03', 'Squid Game'),
 ('2021-09-26', 'Squid Game'),
 ('2021-09-19', 'Lucifer'),
 ('2021-09-12', 'Clickbait'),
 ('2021-09-05', 'Clickbait'),
 ('2021-08-29', 'Clickbait'),
 ('2021-08-22', 'All American'),
 ('2021-08-15', 'Outer Banks'),
 ('2021-08-08', 'Outer Banks'),
 ('2021-08-01', 'Outer Banks'),
 ('2021-07-25', 'Virgin River'),
 ('2021-07-18', 'Virgin River'),
 ('2021-07-11', 'Manifest'),
 ('2021-07-04', 'Manifest')]

### GROUP BY

Idea: for each country, how many unique shows are there at Top 1?

In [32]:

query = """

SELECT country, COUNT(DISTINCT show_title) AS number_shows FROM simple
WHERE category == 'TV' AND rank == 1 
GROUP BY country
"""

cursor.execute(query)
cursor.fetchall()

[('AE', 125),
 ('AR', 123),
 ('AT', 121),
 ('AU', 127),
 ('BD', 98),
 ('BE', 127),
 ('BG', 98),
 ('BH', 127),
 ('BO', 117),
 ('BR', 141),
 ('BS', 146),
 ('CA', 128),
 ('CH', 127),
 ('CL', 123),
 ('CO', 108),
 ('CR', 119),
 ('CY', 122),
 ('CZ', 116),
 ('DE', 118),
 ('DK', 122),
 ('DO', 128),
 ('EC', 118),
 ('EE', 109),
 ('EG', 95),
 ('ES', 116),
 ('FI', 121),
 ('FR', 123),
 ('GB', 131),
 ('GP', 140),
 ('GR', 122),
 ('GT', 121),
 ('HK', 115),
 ('HN', 117),
 ('HR', 133),
 ('HU', 128),
 ('ID', 111),
 ('IE', 142),
 ('IL', 112),
 ('IN', 86),
 ('IS', 136),
 ('IT', 118),
 ('JM', 136),
 ('JO', 113),
 ('JP', 99),
 ('KE', 130),
 ('KR', 105),
 ('KW', 121),
 ('LB', 105),
 ('LK', 116),
 ('LT', 104),
 ('LU', 131),
 ('LV', 104),
 ('MA', 125),
 ('MQ', 140),
 ('MT', 128),
 ('MU', 130),
 ('MV', 119),
 ('MX', 127),
 ('MY', 126),
 ('NC', 146),
 ('NG', 110),
 ('NI', 124),
 ('NL', 119),
 ('NO', 121),
 ('NZ', 128),
 ('OM', 118),
 ('PA', 125),
 ('PE', 119),
 ('PH', 107),
 ('PK', 103),
 ('PL', 130),
 ('PT', 117),
 ('PY', 123),
 ('QA', 128),
 ('RE', 144),
 ('RO', 146),
 ('RS', 112),
 ('RU', 12),
 ('SA', 121),
 ('SE', 118),
 ('SG', 116),
 ('SI', 108),
 ('SK', 128),
 ('SV', 120),
 ('TH', 120),
 ('TR', 111),
 ('TT', 132),
 ('TW', 113),
 ('UA', 118),
 ('US', 134),
 ('UY', 125),
 ('VE', 132),
 ('VN', 98),
 ('ZA', 128)]

### HAVING

Idea: building on top of the previous query, where are the countries that just REALLY love a few TV shows?

In [33]:

query = """

SELECT country, COUNT(DISTINCT show_title) AS number_shows FROM simple
WHERE category == 'TV' AND rank == 1 
GROUP BY country
HAVING number_shows < 90
"""

cursor.execute(query)
cursor.fetchall()

[('IN', 86), ('RU', 12)]